#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 <<EOSQL
CREATE DATABASE magnet;

CREATE USER magnetic WITH
    PASSWORD '$MAGNET_POSTGRES_PASSWORD'
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    LOGIN;

REVOKE ALL ON DATABASE magnet FROM PUBLIC;
GRANT CONNECT ON DATABASE magnet TO magnetic;
EOSQL