\c magnet

-- public schema
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO magnetic;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO magnetic;

-- future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO magnetic;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO magnetic;

-- drive schema
GRANT USAGE ON SCHEMA drive TO magnetic;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA drive TO magnetic;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA drive TO magnetic;

-- future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA drive
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO magnetic;
ALTER DEFAULT PRIVILEGES IN SCHEMA drive
    GRANT USAGE, SELECT ON SEQUENCES TO magnetic;